name: CI/CD Workflow

on:
  push:
    branches:
      - main  # Déclenche le workflow sur les push dans la branche main
      
  pull_request:
    branches:
      - main  # Déclenche le workflow sur les pull requests dans la branche main

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Spécifie que le job doit s'exécuter sur la dernière version d'Ubuntu

    steps:
      - uses: actions/checkout@v4
        # Utilise la dernière version de checkout

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
        # Configure Python 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        # Installe les dépendances définies dans requirements.txt si ce fichier existe

      - name: Run tests
        run: |
          pytest
        # Exécute les tests du projet, en supposant que pytest est utilisé

      - name: Deploy
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          echo "Deploying to production server..."
          # Ajoutez ici votre script de déploiement
        # S'assure que cette étape utilise des variables d'environnement ou d'autres méthodes sécurisées pour gérer les identifiants


