name: CI/CD Workflow

on:
  push:
    branches:
      - main  # Exécute le workflow pour les commits sur la branche 'main'
  pull_request:
    branches:
      - main  # Exécute le workflow pour les pull requests vers la branche 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Utilise la dernière version d'Ubuntu disponible sur GitHub Actions

    steps:
      - uses: actions/checkout@v3  # Assurez-vous que cette version est la dernière et qu'elle est compatible avec Node.js 20

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'  # Spécifie la version de Python à utiliser

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Met à jour pip
          pip install pytest  # Installe pytest pour les tests

      - name: Run tests
        run: pytest  # Exécute les tests unitaires avec pytest
