name: CI/CD Workflow

on:
  push:
    branches:
      - main  # Spécifie que le workflow doit s'exécuter uniquement sur les push vers la branche 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Spécifie que le job doit s'exécuter sur la dernière version d'Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Utilise la dernière version stable de l'action checkout

      - name: Fetch latest release version
        id: latest-release  # Identifie cette étape pour que ses sorties puissent être utilisées plus tard
        uses: reloc8/action-latest-release-version@1.0.0  # Utilise la version spécifiée de l'action pour récupérer la dernière version publiée

      - name: Print the latest release version
        run: echo "The latest release version is ${{ steps.latest-release.outputs.latest-release }}"

      - name: Deploy application
        run: |
          echo "Deploying application version ${{ steps.latest-release.outputs.latest-release }}"
          # Ajoutez ici votre script de déploiement ou toute autre commande utilisant la version récupérée

