name: CI/CD Workflow

on:
  push:
    branches:
      - main  # Triggers the workflow on pushes to the main branch
      
  pull_request:
    branches:
      - main  # Triggers the workflow on pull requests to the main branch
  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Specifies that the job should run on the latest version of Ubuntu

    steps:
      - uses: actions/checkout@v4
        # Uses the latest version of checkout that supports Node.js 20

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
        # Sets up Node.js 20, ensuring compatibility with the latest features and security patches

      - name: Install dependencies
        run: |
          npm install  # Installs npm dependencies defined in package.json
          # Ensure your package.json has the correct versions that support Node.js 20

      - name: Run tests
        run: npm test
        # Runs your project's tests, replace 'npm test' with your specific test command if different

      - name: Build
        run: npm build
        # Add your build script if applicable

      - name: Deploy
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          # Your deployment script here
          echo "Deploying to production server..."
        # Ensure this step uses environment variables or other secure methods to handle credentials

