name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Fetch latest release version
        id: latest-release
        uses: reloc8/action-latest-release-version@1.0.0

      - name: Set release version in environment
        run: echo "LATEST_RELEASE=${{ steps.latest-release.outputs.latest-release }}" >> $GITHUB_ENV

      - name: Print the latest release version
        run: echo "The latest release version is $LATEST_RELEASE"

      - name: Deploy application
        run: |
          echo "Deploying application version $LATEST_RELEASE"
          # Your deployment script here
