name: CI

# Déclencheurs pour le workflow: exécuté sur les pushs et pull requests sur la branche principale
on:
  push:
    branches: [ main ]  # Exécute le workflow pour les commits sur la branche 'main'
  pull_request:
    branches: [ main ]  # Exécute le workflow pour les pull requests vers la branche 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Utilise la dernière version d'Ubuntu disponible sur GitHub Actions

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Utilise la version 3 de l'action checkout, assurée compatible avec Node.js 20

    - name: action-latest-release-version
      uses: reloc8/action-latest-release-version@v1.0.0 
      with:
        python-version: '3.9'  # Spécifie la version de Python à utiliser

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Met à jour pip
        pip install pytest  # Installe pytest pour les tests

    - name: Run tests
      run: pytest  # Exécute les tests unitaires avec pytest
